services:
  app:
    image: ${APP_NAME}-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-app
    environment:
      - PHP_WORKER_INSTALL_BCMATH=true
      - XDEBUG_MODE=off
    working_dir: /var/www
    volumes:
      - ./../:/var/www
      - ./php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    networks:
      - internal

  web:
    image: nginx:alpine
    container_name: ${APP_NAME}-web
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./../:/var/www
      - ./docker/nginx:/etc/nginx/conf.d # Здесь должен лежать ваш nginx-конфиг
      - ./logs/nginx:/var/log/nginx # Логи для поддоменов
    depends_on:
      - app
    networks:
      - internal

networks:
  internal:
    driver: bridge
